name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths-ignore:
      - 'charts/**'

permissions:
  contents: read

jobs:
  ci-rails:
    name: ci-rails
    uses: ./.github/workflows/ci-rails.yml

  ci-mobile:
    name: ci-mobile
    uses: ./.github/workflows/ci-mobile.yml
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'mobile')

  ops-security:
    name: ops-security
    uses: ./.github/workflows/ops-security.yml
